# Generated by Django 4.2.3 on 2023-07-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
